name: Build and Deploy Client
description: Build Next app & deploy to S3 with invalidation

inputs:
  branch:
    description: This is the base name of the S3 deployment bucket
    required: true
  distributionId:
    description: This is the base name of the S3 deployment bucket
    required: true
  s3Bucket:
    description: This is the base name of the S3 deployment bucket
    required: true

runs:
  using: composite
  steps:
    - name: Build and Deploy Client
      id: build-and-deploy-client
      run: |
        echo "branch: ${{ inputs.branch }}"
        echo "deployment bucket: ${{ inputs.s3Bucket }}"

        S3_BUCKET=${{ inputs.s3Bucket }} npm run deploy -w client
        DISTRIBUTION_ID=${{ inputs.distributionId }} aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*' --no-cli-pager
      shell: bash
