name: Build and Deploy Client
description: Build Next app & deploy to S3 with invalidation

inputs:
  algoliaAppId:
    description: 'Algolia app id secret'
    required: true
  contentApi:
    description: AWS content API url
    required: true
  distributionId:
    description: This is the CloudFront distribution id
    required: true
  s3Bucket:
    description: This is the base name of the S3 deployment bucket
    required: true
  userPoolId:
    description: This is the Cognito user pool id
    required: true
  userPoolClientId:
    description: This is the Cognito user pool client id
    required: true

runs:
  using: composite
  steps:
    - name: Build and Deploy Client
      id: build-and-deploy-client
      run: |
        echo "branch: ${{ github.ref_name }}"
        echo "deployment bucket: ${{ inputs.s3Bucket }}"
        echo "distribution id: ${{ inputs.distributionId }}"

        NEXT_PUBLIC_AWS_CONTENT_API=${{ inputs.contentApi }} \
          NEXT_PUBLIC_ALGOLIA_APP_ID=${{ inputs.algoliaAppId }} \
          NEXT_PUBLIC_COGNITO_USER_POOL_ID=${{ inputs.userPoolId }} \
          NEXT_PUBLIC_COGNITO_APP_CLIENT_ID=${{ inputs.userPoolClientId }} 
          S3_BUCKET=${{ inputs.s3Bucket }} \
          npm run deploy -w client

        DISTRIBUTION_ID=${{ inputs.distributionId }} \
          npm run invalidate -w client
      shell: bash
