name: Configure Default User
description: Use admin to create default user and change password

inputs:
  awsDefaultRegion:
    description: AWS default region
    required: true
  userPoolId:
    description: Cognito User Pool id
    required: true
  user:
    description: Email address to use for default user id
    required: true
  password:
    description: Password to change to for default user
    required: true

runs:
  using: 'node16'
  main: 'index.mjs'
