name: Setup
description: This is an action to setup the environment in a workflow.

runs:
  using: composite
  steps:
    # - name: Checkout Repo
    #   id: checkout-repo
    #   uses: actions/checkout@v3

    - name: Use Node.js version in .nvmrc
      id: set-node-version
      uses: actions/setup-node@v3
      with:
        node-version-file: ${{ env.NODE_VERSION_FILE }}
        cache: 'npm'

    - name: Node Cache
      id: node-cache
      uses: actions/cache@v3
      env:
        cache-name: node-cache
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ github.repository }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ github.repository }}-${{ env.cache-name }}-
          ${{ github.repository }}-

    - name: Install Dependencies
      id: install-dependencies
      run: npm ci --ignore-scripts
      shell: bash
