name: Remove Client
description: Removes statically-generated files from S3 bucket

inputs:
  branch:
    description: This is the base name of the S3 deployment bucket
    required: true
  s3Bucket:
    description: This is the base name of the S3 deployment bucket
    required: true

runs:
  using: composite
  steps:
    - name: Remove Client
      id: remove-client
      working-directory: './'
      # env:
      #   BRANCH: ${{ github.ref }}
      #   S3_BUCKET: ${{ steps.bucket-name.outputs.bucketName }}
      run: |
        echo "branch: ${{ inputs.branch }}"
        echo "s3Bucket: ${{ inputs.s3Bucket }}"

        aws s3 rm --recursive ${{ inputs.s3Bucket }}/branches/${{ inputs.branch }}
      shell: bash
