name: Remove Client
description: Removes statically-generated files from S3 bucket

inputs:
  s3Bucket:
    description: This is the base name of the S3 deployment bucket
    required: true

runs:
  using: composite
  steps:
    - name: Remove Client
      id: remove-client
      working-directory: './'
      run: |
        echo "branch: ${{ github.event.ref }}"
        echo "s3Bucket: ${{ inputs.s3Bucket }}"

        aws s3 rm --recursive ${{ inputs.s3Bucket }}/branches/${{ github.event.ref }}
      shell: bash
