name: Get Bucket Name
description: This is an action to get the S3 deployment bucket for the workflow.

inputs:
  bucketBase:
    description: This is the base name of the S3 deployment bucket
    required: true

runs:
  using: composite
  steps:
    - name: Get Bucket Name
      id: bucket-name
      uses: actions/github-script@v6
      with:
        env:
          S3_BUCKET_BASE: ${{ inputs.bucketBase }}
        result-encoding: string
        script: |
          console.log(process.env);

          const { S3_BUCKET_BASE } = process.env;

          console.log('S3_BUCKET_BASE:', S3_BUCKET_BASE);

          const { ref } = context;
          const refArray = ref.split('/');
          const branch = refArray[refArray.length - 1];
          console.log('branch:', branch);

          const bucketName = `${ S3_BUCKET_BASE }-${ branch === 'main' ? 'prod' : 'dev' }`
          console.log('bucketName:', bucketName);

          return bucketName;
