name: Get Bucket Name
description: This is an action to get the S3 deployment bucket for the workflow.

inputs:
  branch:
    description: name of this git branch
    required: true
  bucketBase:
    description: This is the base name of the S3 deployment bucket
    required: true
outputs:
  bucketName:
    description: 'S3 deployment bucket name'
    value: ${{ steps.set-outputs.outputs.bucketName }}

# Bucket name should be looked up from shared resources outputs

runs:
  using: composite
  steps:
    - name: Get Bucket Name
      id: bucket-name
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const bucketBase = '${{ inputs.bucketBase }}';
          console.log('bucketBase:', bucketBase);

          const branch = '${{ inputs.branch }}'
          console.log('branch:', branch);

          const envLabel = (branch === 'main') && 'prod' || 'dev';
          const bucketName = `${ bucketBase }-${ envLabel }`;

          console.log('bucketName:', bucketName);

          return bucketName;
    - name: Set outputs
      id: set-outputs
      run: |
        echo "bucketName = ${{ steps.bucket-name.outputs.result }}"
        echo "bucketName=${{ steps.bucket-name.outputs.result }}" >> $GITHUB_OUTPUT
      shell: bash
