name: Distribution ID
description: This is an action to get the CloudFront distribution id for the workflow.

outputs:
  distributionId:
    description: 'Cloudfront distribution id'
    value: ${{ steps.set-outputs.outputs.distributionId }}

runs:
  using: composite
  steps:
    - name: Get Distribution ID
      id: distribution-id
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const CloudFormation = require('aws-sdk/clients/cloudformation');
          const apiVersion = '2010-05-15';
          const region = 'us-east-1';
          const cloudFormation = new CloudFormation({ apiVersion, region });

          const refArray = context.ref.split('/');
          console.log('refArray:', refArray);

          const branch = refArray[refArray.length - 1];
          console.log('branch:', branch);

          let stackLabel;

          if (branch === 'main') {
            stackLabel = 'Prod';
          } else {
            stackLabel = branch[0].toUpperCase() + branch.slice(1);
          }

          console.log('stackLabel:', stackLabel);

          const stackName = `RecipesBranchStack${ stackLabel }`
          console.log('stackName:', stackName);

          let branchLabel;

          if (branch === 'main') {
            branchLabel = 'Main';
          } else {
            branchLabel = stackLabel.replaceAll('-', '');
          }

          console.log('branchLabel:', branchLabel);

          const distributionLabel = `ExportRecipesDistribution${ branchLabel }`
          console.log('distributionLabel:', distributionLabel);

          const result = await cloudFormation.describeStacks({ StackName: stackName }).promise();
          const foundStacks = (result && result.Stacks) || [];
          const stack = foundStacks.find(s => s.StackName === stackName);

          if (!stack) throw new Error(`Unable to find stack "${stackName}" in region "${region}"`);

          const distributionId = stack.Outputs.find(({ OutputKey }) => OutputKey === distributionLabel).OutputValue;
          console.log('distributionId:', distributionId);

          return distributionId;
    - name: Set outputs
      id: set-outputs
      run: |
        echo "distributionId = ${{ steps.distribution-id.outputs.result }}"
        echo "distributionId=${{ steps.distribution-id.outputs.result }}" >> $GITHUB_OUTPUT
      shell: bash
