name: Setup npm Cache
description: This is an action to setup the npm cache in a workflow.

runs:
  using: composite
  steps:
    - name: Node Cache
      id: node-cache
      uses: actions/cache@v3
      env:
        cache-name: node-cache
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ github.repository }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ github.repository }}-${{ env.cache-name }}-
          ${{ github.repository }}-
