name: Setup Next Build Cache
description: This is an action to setup the Next build cache in a workflow.

runs:
  using: composite
  steps:
    - name: Nextjs Build Cache
      id: next-build-cache
      env:
        cache-name: build-cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/client/.next/cache
        # ${{ github.workspace }}/node_modules
        # Generate a new cache whenever packages or source files change.
        key: ${{ github.repository }}-${{ env.cache-name }}-${{ hashFiles('client/**.[jt]s', 'client/**.[jt]sx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ github.repository }}-${{ env.cache-name }}-
          ${{ github.repository }}-
