name: Build and Deploy
run-name: Build and Deploy

on:
  workflow_dispatch:
  # Allows external webhook trigger with "event_type" = "publish-event"
  repository_dispatch:
    types: [publish-event]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.ref }}
  cancel-in-progress: true

env:
  ALGOLIA_SEARCH_ADMIN_KEY: ${{ secrets.ALGOLIA_SEARCH_ADMIN_KEY }}
  BUILD_BRANCH: ${{ github.event.client_payload.build_branch || github.ref_name}}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CONTENTFUL_MANAGEMENT_API: ${{ vars.CONTENTFUL_MANAGEMENT_API }}
  CONTENTFUL_MANAGEMENT_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  NEXT_PUBLIC_ALGOLIA_APP_ID: ${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}
  NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY }}
  NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  NEXT_PUBLIC_CONTENTFUL_CONTENT_API: https://graphql.contentful.com/content/v1/spaces/${{secrets.CONTENTFUL_SPACE_ID}}/
  NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  NEXT_PUBLIC_SITE_URL: ${{ github.ref_name == 'main' && vars.NEXT_PUBLIC_SITE_URL || format('{0}{1}{2}', 'https://', github.ref_name, '.recipes.pliddy.com') }}
  NODE_VERSION_FILE: '.nvmrc'
  S3_BUCKET_BASE: ${{ vars.S3_BUCKET_BASE }}

jobs:
  BuildAndDeploySite:
    name: Build and Deploy Site
    runs-on: ubuntu-latest
    steps:
      - name: Display Branch Labels
        id: test-branch-labels
        run: |
          echo "github.event.ref: ${{ github.event.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "BUILD_BRANCH: "${{ env.BUILD_BRANCH }}"

      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v3
        with:
          ref: ${{ BUILD_BRANCH }}

      - name: Setup Node
        id: setup-node
        uses: './.github/actions/setup-node'

      - name: Setup npm cache
        id: npm-cache
        uses: './.github/actions/npm-cache'

      - name: Setup Next
        id: setup-next
        uses: './.github/actions/next-build-cache'

      # TODO: set correct branch for
      - name: Install Dependencies
        id: install-dependencies
        uses: './.github/actions/install-dependencies'

      - name: Get Bucket Name
        id: bucket-name
        uses: './.github/actions/bucket-name'
        with:
          branch: ${{ github.ref_name }}
          bucketBase: ${{ vars.S3_BUCKET_BASE }}

      - name: Get Distribution ID
        id: distribution-id
        uses: './.github/actions/distribution-id'

      - name: Get User Pool IDs
        id: user-pool-ids
        uses: './.github/actions/user-pool-ids'

      - name: Get AWS Content API
        id: content-api-url
        uses: './.github/actions/content-api'

      - name: Build and Deploy Client
        id: build-and-deploy-client
        uses: './.github/actions/build-and-deploy-client'
        with:
          algoliaAppId: ${{ env.NEXT_PUBLIC_ALGOLIA_APP_ID }}
          contentApi: ${{ steps.content-api-url.outputs.contentApi }}
          distributionId: ${{ steps.distribution-id.outputs.distributionId }}
          s3Bucket: ${{ steps.bucket-name.outputs.bucketName }}
          userPoolId: ${{ steps.user-pool-ids.outputs.userPoolId }}
          userPoolClientId: ${{ steps.user-pool-ids.outputs.userPoolClientId }}

      - name: Build Search Index
        id: index-search
        uses: './.github/actions/index-search'
        with:
          algoliaAppId: ${{ env.NEXT_PUBLIC_ALGOLIA_APP_ID }}
          algoliaSearchAdminKey: ${{ env.ALGOLIA_SEARCH_ADMIN_KEY }}
          contentfulAccessToken: ${{ env.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN }}
          contentfulSpaceId: ${{ env.NEXT_PUBLIC_CONTENTFUL_SPACE_ID }}
