name: Create User
run-name: Create User

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION_FILE: '.nvmrc'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DEFAULT_USER: ${{ vars.DEFAULT_USER }}
  DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}

jobs:
  CreateUser:
    name: Create Cognito User
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v4

      - name: Setup Node
        id: setup-node
        uses: './.github/actions/setup-node'

      - name: Setup npm cache
        id: npm-cache
        uses: './.github/actions/npm-cache'

      - name: Install Dependencies
        id: install-dependencies
        uses: './.github/actions/install-dependencies'

      - name: Get User Pool IDs
        id: user-pool-ids
        uses: './.github/actions/user-pool-ids'

      - name: Create Default User
        id: create-default-user
        uses: './.github/actions/default-user'
        with:
          awsDefaultRegion: ${{ env.AWS_DEFAULT_REGION }}
          userPoolId: ${{ steps.user-pool-ids.outputs.userPoolId }}
          user: ${{ env.DEFAULT_USER }}
          password: ${{ env.DEFAULT_PASSWORD }}
