name: Build and Deploy
run-name: Build and Deploy

# {
#   "event_type": "publish-event",
#   "client_payload": {
#     "timestamp": "scheduled_publish_timestamp"
#   }
# }

# jobs:
#   test_client_payload:
#     if: ${{ !github.event.client_payload.passed }}
#     runs-on: ubuntu-latest
#     steps:
#       - env:
#           MESSAGE: ${{ github.event.client_payload.message }}
#         run: echo $MESSAGE

on:
  push:
    branches:
      - main
  workflow_dispatch:
  # Allows external webhook trigger with "event_type" = "publish-event"
  repository_dispatch:
    types: [publish-event]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION_FILE: '.nvmrc'

jobs:
  test:
    name: Test Webhook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: 'echo "timestamp: ${{ github.event.client_payload.timestamp }}"'
        if: github.event.event_type === 'publish-event'
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version in .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache: 'npm'
      - name: Project Cache
        id: project-cache
        uses: actions/cache@v3
        env:
          cache-name: project-cache
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            ${{ github.workspace }}/node_modules
          key: ${{ github.repository }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ github.repository }}-${{ env.cache-name }}-
            ${{ github.repository }}-
      - name: Nextjs Build Cache
        id: build-cache
        env:
          cache-name: build-cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ github.repository }}-${{ env.cache-name }}-${{ hashFiles('.next/cache/**/*.*') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ github.repository }}-${{ env.cache-name }}-
            ${{ github.repository }}-
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Build and Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          DISTRIBUTION_ID: ${{secrets.DISTRIBUTION_ID}}
          NEXT_PUBLIC_API_ENDPOINT: https://graphql.contentful.com/content/v1/spaces/${{secrets.CONTENTFUL_SPACE_ID}}/
          NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          S3_BUCKET: ${{secrets.S3_BUCKET}}
        run: npm run deploy
