name: Deploy Branch AWS Resources
run-name: Deploy Branch AWS Resources

on:
  create:
    branches:
      - '!main'
  workflow_dispatch:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION_FILE: '.nvmrc'

jobs:
  deployStack:
    if: github.event.ref_type == 'branch' && github.event.ref != 'main'
    name: Deploy Stack
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Use Node.js version in .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache: 'npm'
      - name: CDK Cache
        id: cdk-cache
        uses: actions/cache@v3
        env:
          cache-name: cdk-cache
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ github.repository }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ github.repository }}-${{ env.cache-name }}-
            ${{ github.repository }}-
      - name: Install Dependencies
        run: cd .github/cdk && npm ci --ignore-scripts
      - name: Deploy Branch-specific Stack for ${{github.event.ref}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: cd .github/cdk && npm run deploy
      - name: Branch Label
        id: branch-label
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.event.ref }}
      - name: Get CDK Outputs
        id: cdk-outputs
        # handle multi-line json
        run: |
          content=`cd .github/cdk && cat ./cdk-outputs.json`
          echo "content: ${content}"
          echo "{cdkOutputs}={$content//'%'/'%25'}" >> $GITHUB_OUTPUT

        # echo "distributionId: ${{ distributionId }}"
        # echo "{distributionId}={$distributionId}" >> $GITHUB_OUTPUT

      - name: Set Distribution Id
        id: distribution-id
        env:
          BRANCH_LABEL: ${{ steps.branch-label.outputs.capitalized }}
          OUTPUT_ID: 'RecipesBranchStack${{ steps.branch-label.outputs.capitalized }}'
          CDK_OUTPUTS: ${{ fromJson(steps.cdk-outputs.outputs.cdkOutputs) }}
          # DISTRIBUTION_ID: '${{ fromJson(steps.cdk-outputs.outputs.cdkOutputs) }}.RecipesBranchStack${{ steps.branch-label.outputs.capitalized }}'
        run: |
          echo "BRANCH_LABEL: $BRANCH_LABEL"
          echo "OUTPUT_ID: $OUTPUT_ID"

          echo "CDK_OUTPUTS: ${ CDK_OUTPUTS }"

          stackLabel = 'RecipesBranchStack$BRANCH_LABEL-deploy-branch'
          resourceLabel = 'ExportRecipesDistribution$BRANCH_LABEL'

          echo "stackLabel: ${{ stackLabel }}"
          echo "resourceLabel: ${{ resourceLabel }}"

          distributionId=$CDK_OUTPUTS[stackLabel][resourceLabel]

          echo "distributionId: ${{ distributionId }}"

        # echo "cdk outputs: ${fromJson(steps.cdk-outputs.outputs.cdkOutputs).ExportRecipesBranchStack087-deploy-shared}"

      #     echo "steps.branch-label.outputs.capitalized: ${{ steps.branch-label.outputs.capitalized }}"

      # echo "{distributionId}={$DISTRIBUTION_ID}" >> $GITHUB_OUTPUT

      # echo "CDK_OUTPUTS: ${{ CDK_OUTPUTS }}"

      # distributionId="${{ cdkOutputs }}.${{ outputId }}"

      # echo "distributionId: ${{ distributionId }}"

      # - name: Deploy Site Content
      #   id: deploy-site-content
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      #     DISTRIBUTION_ID: ${{steps.distribution-id.distributionId}}
      #     S3_BUCKET: recipes.pliddy.com-dev # update based on branch name
      #   run: |
      #     npm run deploy
