name: Scan and Build Branch
run-name: Scan and Build Branch

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION_FILE: '.nvmrc'

jobs:
  DeployBranch:
    name: Deploy Branch Stack to AWS
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      NEXT_PUBLIC_API_ENDPOINT: https://graphql.contentful.com/content/v1/spaces/${{secrets.CONTENTFUL_SPACE_ID}}/
      NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
    steps:
      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: './.github/actions/setup-node'

      - name: Setup Next
        uses: './.github/actions/next-build-cache'

      - name: Install Dependencies
        uses: './.github/actions/install-dependencies'

      - name: Run Scans on the CDK Workspace
        uses: './.github/actions/scan-cdk'

      - name: Run Scans on the Client Workspace
        uses: './.github/actions/scan-clients'

      - name: Deploy Shared AWS Stack for ${{github.event.ref}}
        id: deploy-shared-stack
        run: npm run deploy:shared -w cdk

      - name: Deploy Branch-specific Stack for ${{github.event.ref}}
        id: deploy-branch-stack
        run: npm run deploy -w cdk

      # Bucket name should be looked up from shared resources outputs

      - name: Get Bucket Name
        id: bucket-name
        uses: actions/github-script@v6
        env:
          S3_BUCKET_BASE: ${{ vars.S3_BUCKET_BASE }}
        with:
          result-encoding: string
          script: |
            const { S3_BUCKET_BASE } = process.env
            console.log('S3_BUCKET_BASE:', S3_BUCKET_BASE);

            const { ref } = context;
            const refArray = ref.split('/');
            const branch = refArray[refArray.length - 1];
            console.log('branch:', branch);

            const bucketName = `${ S3_BUCKET_BASE }-${ branch === 'main' ? 'prod' : 'dev' }`
            console.log('bucketName:', bucketName);

            return bucketName;

      - name: Get Distribution ID
        id: distribution-id
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const CloudFormation = require('aws-sdk/clients/cloudformation');
            const apiVersion = '2010-05-15';
            const region = 'us-east-1';
            const cloudFormation = new CloudFormation({ apiVersion, region });

            const refArray = context.ref.split('/');
            console.log('refArray:', refArray);

            const branch = refArray[refArray.length - 1];
            console.log('branch:', branch);

            let stackLabel;

            if (branch === 'main') {
              stackLabel = 'Prod';
            } else {
              stackLabel = branch[0].toUpperCase() + branch.slice(1);
            }

            console.log('stackLabel:', stackLabel);

            const stackName = `RecipesBranchStack${ stackLabel }`
            console.log('stackName:', stackName);

            let branchLabel;

            if (branch === 'main') {
              branchLabel = 'Main';
            } else {
              branchLabel = stackLabel.replaceAll('-', '');
            }

            console.log('branchLabel:', branchLabel);

            const distributionLabel = `ExportRecipesDistribution${ branchLabel }`
            console.log('distributionLabel:', distributionLabel);

            const result = await cloudFormation.describeStacks({ StackName: stackName }).promise();
            const foundStacks = (result && result.Stacks) || [];
            const stack = foundStacks.find(s => s.StackName === stackName);

            if (!stack) throw new Error(`Unable to find stack "${stackName}" in region "${region}"`);

            const distributionId = stack.Outputs.find(({ OutputKey }) => OutputKey === distributionLabel).OutputValue;
            console.log('distributionId:', distributionId);

            return distributionId;

      - name: Build and Deploy Client
        id: build-and-deploy-client
        env:
          BRANCH: ${{ github.ref_name }}
          DISTRIBUTION_ID: ${{ steps.distribution-id.outputs.result }}
          S3_BUCKET: ${{ steps.bucket-name.outputs.result }}
        run: |
          echo "branch: $BRANCH"
          echo "deployment bucket: $S3_BUCKET"

          npm run deploy -w client
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*' --no-cli-pager
