name: Deploy Shared AWS Resources
run-name: Deploy Shared AWS Resources

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION_FILE: '.nvmrc'

#
#   STEPS FOR SCANS JOB
#
#   - checkout-repo
#   - set-node-version
#   - node-cache
#   - install-dependencies
#   - run-scans-cdk
#
#   STEPS FOR DEPLOY SHARED STACKS JOB
#
#   - checkout-repo
#   - set-node-version
#   - node-cache
#   - install-dependencies
#   - deploy-shared-stack
#

jobs:
  # Scans:
  #   name: Run Code Quality Scans
  #   runs-on: ubuntu-latest
  #   env:
  #     NEXT_PUBLIC_API_ENDPOINT: https://graphql.contentful.com/content/v1/spaces/${{secrets.CONTENTFUL_SPACE_ID}}/
  #     NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  #     NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  #     NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
  #   steps:
  #     - name: Checkout Repo
  #       id: checkout-repo
  #       uses: actions/checkout@v3
  #     - name: Use Node.js version in .nvmrc
  #       id: set-node-version
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version-file: ${{ env.NODE_VERSION_FILE }}
  #         cache: 'npm'
  #     - name: Node Cache
  #       id: node-cache
  #       uses: actions/cache@v3
  #       env:
  #         cache-name: node-cache
  #       with:
  #         # npm cache files are stored in `~/.npm` on Linux/macOS
  #         path: ~/.npm
  #         key: ${{ github.repository }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ github.repository }}-${{ env.cache-name }}-
  #           ${{ github.repository }}-
  #     - name: Install Dependencies
  #       id: install-dependencies
  #       run: npm ci --ignore-scripts
  #     - name: Run Scans on the CDK Workspace
  #       id: run-scans-cdk
  #       run: |
  #         npm run scan -w cdk

  DeploySharedStack:
    name: Deploy Shared Stack to AWS
    runs-on: ubuntu-latest
    # needs: [Scans]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      NEXT_PUBLIC_API_ENDPOINT: https://graphql.contentful.com/content/v1/spaces/${{secrets.CONTENTFUL_SPACE_ID}}/
      NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
    steps:
      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v3

      - name: Use Node.js version in .nvmrc
        id: set-node-version
        uses: actions/setup-node@v3
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache: 'npm'

      - name: Node Cache
        id: node-cache
        uses: actions/cache@v3
        env:
          cache-name: node-cache
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ github.repository }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ github.repository }}-${{ env.cache-name }}-
            ${{ github.repository }}-

      - name: Install Dependencies
        id: install-dependencies
        run: npm ci --ignore-scripts

      - name: Run Scans on the CDK Workspace
        id: run-scans-cdk
        run: npm run scan -w cdk

      - name: Deploy Shared AWS Stack for ${{github.event.ref}}
        id: deploy-shared-stack
        run: npm run deploy:shared
