name: Build and Deploy
run-name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  NODE_VERSION_FILE: '.nvmrc'

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version specified in .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache: 'npm'
      - name: CI install
        run: npm ci
      - name: npm Install
        run: npm install
      # - name: Change to root directory
      #   uses: ./
      #   run: cd ./next-recipes
      - name: Build and Deploy
        env:
          NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          NEXT_PUBLIC_API_ENDPOINT: https://graphql.contentful.com/content/v1/spaces/${{secrets.CONTENTFUL_SPACE_ID}}/
          DISTRIBUTION_ID: ${{secrets.DISTRIBUTION_ID}}
          S3_BUCKET: ${{secrets.S3_BUCKET}}
        run: npm run deploy
