name: Deploy Shared AWS Resources
run-name: Deploy Shared AWS Resources

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION_FILE: '.nvmrc'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  NEXT_PUBLIC_API_ENDPOINT: https://graphql.contentful.com/content/v1/spaces/${{secrets.CONTENTFUL_SPACE_ID}}/
  NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  NEXT_PUBLIC_SITE_URL: ${{ github.ref_name == 'main' && vars.NEXT_PUBLIC_SITE_URL || format('{0} {1} {2}', 'https://', github.ref_name, 'recipes.pliddy.com') }}

jobs:
  DeploySharedStack:
    name: Deploy Shared Stack to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v3

      - name: Setup Node
        id: setup-node
        uses: './.github/actions/setup-node'

      - name: Setup npm cache
        id: npm-cache
        uses: './.github/actions/npm-cache'

      - name: Install Dependencies
        id: install-dependencies
        uses: './.github/actions/install-dependencies'

      - name: Run Scans on the CDK Workspace
        id: scan-cdk
        uses: './.github/actions/scan-cdk'

      - name: Deploy Shared AWS Stack for ${{github.ref}}
        id: deploy-shared-stack
        run: npm run deploy:shared
