name: Build and Deploy
run-name: Build and Deploy

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  pull_request:
    types:
      - closed

env:
  NODE_VERSION_FILE: '.nvmrc'

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version specified in .nvmrc
        uses: ./
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache: 'npm'
      - name: CI install
        run: npm ci
      - name: npm Install
        run: npm install
      # - name: Change to root directory
      #   run: cd ./next-recipes
      - name: Build and Deploy
        env:
          DISTRIBUTION_ID: ${{secrets.DISTRIBUTION_ID}}
          S3_BUCKET: ${{secrets.S3_BUCKET}}
        run: npm run deploy
