name: Destroy Branch
run-name: Destroy Branch

on:
  delete:
    branches:
      - '!main'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION_FILE: '.nvmrc'

jobs:
  DestroyBranchStack:
    name: Destroy Branch Stack on AWS
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_BASE: ${{ vars.S3_BUCKET_BASE }}
    steps:
      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: './.github/actions/setup-node'

      - name: Destroy AWS
        id: destroy-branch-stack
        env:
          BRANCH: ${{ github.event.ref }}
        run: |
          echo "branch: $BRANCH"
          echo "SOURCE_BRANCH=$BRANCH" >> $GITHUB_OUTPUT

          npm run destroy -w cdk

      - name: Get Bucket Name
        uses: './.github/actions/bucket-name'
        with:
          bucketBase: ${{ vars.S3_BUCKET_BASE }}

      - name: Remove Files
        id: remove-files
        working-directory: './'
        env:
          BRANCH: ${{ github.ref }}
          S3_BUCKET: ${{ steps.bucket-name.outputs.result }}
        run: |
          echo "BRANCH: $BRANCH"
          echo "S3_BUCKET: $S3_BUCKET"

          aws s3 rm --recursive $S3_BUCKET/branches/$BRANCH
