name: Destroy Branch
run-name: Destroy Branch

on:
  delete:
    branches:
      - '!main'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION_FILE: '.nvmrc'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET_BASE: ${{ vars.S3_BUCKET_BASE }}

jobs:
  DestroyBranchStack:
    name: Destroy Branch Stack on AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v3

      - name: Test Branch Labels
        id: test-branch-labels
        run: |
          echo "github.event.ref: ${{ github.event.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"

      - name: Setup Node
        id: setup-node
        uses: './.github/actions/setup-node'

      - name: Setup npm cache
        id: npm-cache
        uses: './.github/actions/npm-cache'

      - name: Install Dependencies
        id: install-dependencies
        uses: './.github/actions/install-dependencies'

      - name: Destroy AWS Stack
        id: destroy-aws-stack
        uses: './.github/actions/destroy-aws-stack'

      - name: Get Bucket Name
        id: bucket-name
        uses: './.github/actions/bucket-name'
        with:
          branch: ${{ github.event.ref }}
          bucketBase: ${{ vars.S3_BUCKET_BASE }}

      - name: Remove Client
        id: remove-client
        uses: './.github/actions/remove-client'
        with:
          s3Bucket: ${{ steps.bucket-name.outputs.bucketName }}
