name: Code Quality Scans
run-name: Code Quality Scans

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION_FILE: '.nvmrc'

jobs:
  Scans:
    name: Run Code Quality Scans
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_ENDPOINT: https://graphql.contentful.com/content/v1/spaces/${{secrets.CONTENTFUL_SPACE_ID}}/
      NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
    steps:
      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v3

      - name: Setup
        uses: './.github/actions/setup'

      - name: Run Scans on the CDK Workspace
        id: run-scans-cdk
        run: npm run scan -w cdk

      - name: Run Scans on the Client Workspace
        id: run-scans-client
        run: npm run scan -w client
