name: Code Quality Scans
run-name: Code Quality Scans

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION_FILE: '.nvmrc'

jobs:
  scan:
    name: Run Code Quality Scans
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version in .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache: 'npm'
      - name: Node Cache
        id: node-cache
        uses: actions/cache@v3
        env:
          cache-name: node-cache
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ github.repository }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ github.repository }}-${{ env.cache-name }}-
            ${{ github.repository }}-
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Run Scans on the CDK Workspace
        run: |
          npm run scan -w cdk
      - name: Run Scans on the Next Workspace
        run: |
          npm run typegen
          npm run scan -w next
      # - name: Typecheck
      #   run: npm run typecheck
      # - name: Lint
      #   run: npm run lint
      # - name: Run Unit Tests
      #   run: npm run test

  # typecheck:
  #   name: Type Check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js version in .nvmrc
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version-file: ${{ env.NODE_VERSION_FILE }}
  #         cache: 'npm'
  #     - name: Node Cache
  #       id: node-cache
  #       uses: actions/cache@v3
  #       env:
  #         cache-name: node-cache
  #       with:
  #         # npm cache files are stored in `~/.npm` on Linux/macOS
  #         path: ~/.npm
  #         key: ${{ github.repository }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ github.repository }}-${{ env.cache-name }}-
  #           ${{ github.repository }}-
  #     - name: Install Dependencies
  #       run: npm ci --ignore-scripts
  # test:
  #   name: Unit Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js version in .nvmrc
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version-file: ${{ env.NODE_VERSION_FILE }}
  #         cache: 'npm'
  #     - name: Node Cache
  #       id: node-cache
  #       uses: actions/cache@v3
  #       env:
  #         cache-name: node-cache
  #       with:
  #         # npm cache files are stored in `~/.npm` on Linux/macOS
  #         path: ~/.npm
  #         key: ${{ github.repository }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ github.repository }}-${{ env.cache-name }}-
  #           ${{ github.repository }}-
  #     - name: Install Dependencies
  #       run: npm ci --ignore-scripts
  #     - name: Run Unit Tests
  #       run: npm run test
